package app;

public class LaunchFrame extends javax.swing.JFrame {

  private String appName;

  /**
   * Creates new form Splash
   */
  public LaunchFrame() {
    initComponents();
    app.Global.setAppIcon(this);
    getAppName();
    lblAppName.setText(appName);
    setSystemTray();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btgTheme = new javax.swing.ButtonGroup();
    pnlContainer = new javax.swing.JPanel();
    lblAppLogo = new javax.swing.JLabel();
    lblAppName = new javax.swing.JLabel();
    pnlActions = new javax.swing.JPanel();
    btnLaunchKiosk = new javax.swing.JButton();
    btnLaunchAdmin = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jTextField1 = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    menuBar = new javax.swing.JMenuBar();
    mnuFile = new javax.swing.JMenu();
    mniExit = new javax.swing.JMenuItem();
    mnuTheme = new javax.swing.JMenu();
    cmuLight = new javax.swing.JCheckBoxMenuItem();
    cmuDark = new javax.swing.JCheckBoxMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Launcher");
    setName(""); // NOI18N
    setPreferredSize(new java.awt.Dimension(720, 600));
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    pnlContainer.setMaximumSize(new java.awt.Dimension(640, 480));
    pnlContainer.setMinimumSize(new java.awt.Dimension(640, 480));
    pnlContainer.setPreferredSize(new java.awt.Dimension(640, 480));
    pnlContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lblAppLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/app-logo-1x.png"))); // NOI18N
    pnlContainer.add(lblAppLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

    lblAppName.setFont(lblAppName.getFont().deriveFont(lblAppName.getFont().getSize()+13f));
    pnlContainer.add(lblAppName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    pnlActions.setMaximumSize(null);
    pnlActions.setPreferredSize(new java.awt.Dimension(420, 180));
    pnlActions.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

    btnLaunchKiosk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/water-heater.png"))); // NOI18N
    btnLaunchKiosk.setText("Launch Kiosk");
    btnLaunchKiosk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnLaunchKiosk.setIconTextGap(20);
    btnLaunchKiosk.setPreferredSize(new java.awt.Dimension(300, 400));
    btnLaunchKiosk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnLaunchKiosk.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLaunchKioskActionPerformed(evt);
      }
    });
    pnlActions.add(btnLaunchKiosk);

    btnLaunchAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/online-test.png"))); // NOI18N
    btnLaunchAdmin.setText("Launch Admin");
    btnLaunchAdmin.setToolTipText("");
    btnLaunchAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnLaunchAdmin.setIconTextGap(20);
    btnLaunchAdmin.setPreferredSize(new java.awt.Dimension(300, 400));
    btnLaunchAdmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnLaunchAdmin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLaunchAdminActionPerformed(evt);
      }
    });
    pnlActions.add(btnLaunchAdmin);

    pnlContainer.add(pnlActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 233, -1, -1));

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jTextField1.setText("127.0.0.1");
    jTextField1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField1ActionPerformed(evt);
      }
    });
    jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, 30));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel1.setText("ip");
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

    pnlContainer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 130, 30));

    getContentPane().add(pnlContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 48, -1, -1));

    mnuFile.setText("File");

    mniExit.setText("Exit");
    mniExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mniExitActionPerformed(evt);
      }
    });
    mnuFile.add(mniExit);

    menuBar.add(mnuFile);

    mnuTheme.setText("Theme");

    btgTheme.add(cmuLight);
    cmuLight.setSelected(true);
    cmuLight.setText("Light");
    cmuLight.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        cmuLightItemStateChanged(evt);
      }
    });
    mnuTheme.add(cmuLight);

    btgTheme.add(cmuDark);
    cmuDark.setText("Dark");
    cmuDark.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        cmuDarkItemStateChanged(evt);
      }
    });
    mnuTheme.add(cmuDark);

    menuBar.add(mnuTheme);

    setJMenuBar(menuBar);

    getAccessibleContext().setAccessibleName("");

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnLaunchAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaunchAdminActionPerformed
    new admin.LoginFrame().setVisible(true);

    // Minimize the LaunchFrame frame
    // setState(javax.swing.JFrame.ICONIFIED);
  }//GEN-LAST:event_btnLaunchAdminActionPerformed

  private void btnLaunchKioskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaunchKioskActionPerformed
    new pos.StartFrame().setVisible(true);

    // Minimize the LaunchFrame frame
    // setState(javax.swing.JFrame.ICONIFIED);
  }//GEN-LAST:event_btnLaunchKioskActionPerformed

  private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
    System.exit(0);
  }//GEN-LAST:event_mniExitActionPerformed

  private void cmuLightItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmuLightItemStateChanged
    setTheme(evt, "light");
  }//GEN-LAST:event_cmuLightItemStateChanged

  private void cmuDarkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmuDarkItemStateChanged
    setTheme(evt, "dark");
  }//GEN-LAST:event_cmuDarkItemStateChanged

  private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField1ActionPerformed

  private void getAppName() {
    try {
      app.PropertiesReader reader = new app.PropertiesReader("properties-from-pom.properties");
      String name = reader.getProperty("name");
      appName = name;
    } catch (java.io.IOException ex) {
      appName = "";
      System.out.println(ex);
    }
  }

  private void setTheme(java.awt.event.ItemEvent evt, String name) {
    if (evt.getStateChange() == 1) {
      if ("light".equals(name)) {
        app.Global.setDefaultTheme();
      } else {
        com.formdev.flatlaf.FlatDarculaLaf.install();
      }
      for (java.awt.Window window : javax.swing.JFrame.getWindows()) {
        javax.swing.SwingUtilities.updateComponentTreeUI(window);
      }
    }
  }

  private void setSystemTray() {
    java.awt.PopupMenu popupMenu = new java.awt.PopupMenu();
    java.awt.TrayIcon trayIcon = new java.awt.TrayIcon(new javax.swing.ImageIcon(getClass().getResource("/app/app-logo-1x.png")).getImage());
    java.awt.SystemTray systemTray = java.awt.SystemTray.getSystemTray();

    java.awt.MenuItem menuItemAbout = new java.awt.MenuItem("About");
    java.awt.MenuItem menuItemExit = new java.awt.MenuItem("Exit");
    popupMenu.add(menuItemAbout);
    popupMenu.add(menuItemExit);

    trayIcon.setImageAutoSize(true);
    trayIcon.setToolTip(appName);
    trayIcon.setPopupMenu(popupMenu);

    try {
      systemTray.add(trayIcon);
    } catch (java.awt.AWTException ex) {
      System.out.println(ex);
      return;
    }

    trayIcon.addActionListener((java.awt.event.ActionEvent evt) -> {
      setState(javax.swing.JFrame.NORMAL);
    });

    menuItemExit.addActionListener((java.awt.event.ActionEvent evt) -> {
      systemTray.remove(trayIcon);
      System.exit(0);
    });
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set default theme */
    app.Global.setDefaultTheme();

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      new LaunchFrame().setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup btgTheme;
  private javax.swing.JButton btnLaunchAdmin;
  private javax.swing.JButton btnLaunchKiosk;
  private javax.swing.JCheckBoxMenuItem cmuDark;
  private javax.swing.JCheckBoxMenuItem cmuLight;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JLabel lblAppLogo;
  private javax.swing.JLabel lblAppName;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenuItem mniExit;
  private javax.swing.JMenu mnuFile;
  private javax.swing.JMenu mnuTheme;
  private javax.swing.JPanel pnlActions;
  private javax.swing.JPanel pnlContainer;
  // End of variables declaration//GEN-END:variables
}
