package admin;

import java.util.logging.Level;
import java.util.logging.Logger;

public class AdminFrame extends javax.swing.JFrame {

  private String ip;

  /**
   * Creates new form AdminFrame
   *
   */
  public AdminFrame() throws ClassNotFoundException {
    initComponents();
    app.Global.setAppIcon(this);
    tabbedPane.addTab("Orders", new OrdersPanel());
    tabbedPane.addTab("Items", new ItemsPanel());
    tabbedPane.addTab("Categories", new CategoriesPanel());
    tabbedPane.addTab("Users", new UsersPanel());
  }

  public AdminFrame(String ip) throws ClassNotFoundException {
    this.ip = ip;
    initComponents();
    app.Global.setAppIcon(this);
    tabbedPane.addTab("Orders", new OrdersPanel());
    tabbedPane.addTab("Items", new ItemsPanel());
    tabbedPane.addTab("Categories", new CategoriesPanel());
    tabbedPane.addTab("Users", new UsersPanel());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    tabbedPane = new javax.swing.JTabbedPane();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Admin");
    setName(""); // NOI18N
    setPreferredSize(new java.awt.Dimension(720, 600));
    getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

    getAccessibleContext().setAccessibleName("");

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set default theme */
    app.Global.setDefaultTheme();

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      try {
        new AdminFrame().setVisible(true);
      } catch (ClassNotFoundException ex) {
        Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTabbedPane tabbedPane;
  // End of variables declaration//GEN-END:variables
}
