package admin;

import java.util.logging.Level;
import java.util.logging.Logger;
import services.clientHandler;

public class LoginFrame extends javax.swing.JFrame {

  services.clientHandler authService;
  private String ip = "127.0.0.1";

  /**
   * Creates new form LoginFrame
   */
  public LoginFrame() {
    initComponents();
    app.Global.setAppIcon(this);
    authService = new services.clientHandler(this.ip);
  }

  public LoginFrame(String ip) {
    this.ip = ip;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    pnlContainer = new javax.swing.JPanel();
    lblTitle = new javax.swing.JLabel();
    lblUsername = new javax.swing.JLabel();
    txtUsername = new javax.swing.JTextField();
    lblPassword = new javax.swing.JLabel();
    txtPassword = new javax.swing.JPasswordField();
    btnLogin = new javax.swing.JButton();
    lblItemImagePreview = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Login");
    setBackground(new java.awt.Color(255, 255, 255));
    setName(""); // NOI18N
    setPreferredSize(new java.awt.Dimension(720, 600));
    getContentPane().setLayout(new java.awt.GridBagLayout());

    pnlContainer.setBackground(new java.awt.Color(255, 255, 255));
    pnlContainer.setPreferredSize(new java.awt.Dimension(400, 200));
    java.awt.GridBagLayout pnlFormLayout = new java.awt.GridBagLayout();
    pnlFormLayout.columnWidths = new int[] {100, 250};
    pnlFormLayout.rowHeights = new int[] {60, 0, 60, 40};
    pnlContainer.setLayout(pnlFormLayout);

    lblTitle.setFont(lblTitle.getFont().deriveFont(lblTitle.getFont().getSize()+10f));
    lblTitle.setForeground(new java.awt.Color(25, 47, 157));
    pnlContainer.add(lblTitle, new java.awt.GridBagConstraints());

    lblUsername.setLabelFor(txtUsername);
    lblUsername.setText("Username");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pnlContainer.add(lblUsername, gridBagConstraints);

    txtUsername.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtUsernameActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    pnlContainer.add(txtUsername, gridBagConstraints);

    lblPassword.setLabelFor(txtPassword);
    lblPassword.setText("Password");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pnlContainer.add(lblPassword, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    pnlContainer.add(txtPassword, gridBagConstraints);

    btnLogin.setBackground(new java.awt.Color(25, 47, 157));
    btnLogin.setForeground(new java.awt.Color(255, 255, 255));
    btnLogin.setText("Log in");
    btnLogin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLoginActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pnlContainer.add(btnLogin, gridBagConstraints);

    lblItemImagePreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblItemImagePreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/8005091691_c52bb4ef-b5b1-4221-a5.png"))); // NOI18N
    lblItemImagePreview.setMaximumSize(new java.awt.Dimension(150, 150));
    lblItemImagePreview.setMinimumSize(new java.awt.Dimension(150, 150));
    lblItemImagePreview.setPreferredSize(new java.awt.Dimension(150, 150));
    pnlContainer.add(lblItemImagePreview, new java.awt.GridBagConstraints());

    getContentPane().add(pnlContainer, new java.awt.GridBagConstraints());

    getAccessibleContext().setAccessibleName("");

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    if (getValidFields()) {
      models.User user = new models.User();
      user.setUsername(txtUsername.getText());
      user.setPassword(new String(txtPassword.getPassword()));

      try {
        if (clientHandler.getAuth(user)) {
          new AdminFrame(this.ip).setVisible(true);
          this.dispose();
        } else {
          javax.swing.JOptionPane.showMessageDialog(null, "Invalid username or password", "Authentication Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
      } catch (ClassNotFoundException ex) {
        Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
  }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

  private boolean getValidFields() {
    if (txtUsername.getText().isEmpty()) {
      javax.swing.JOptionPane.showMessageDialog(null, "Username is required", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
      return false;
    } else if (new String(txtPassword.getPassword()).isEmpty()) {
      javax.swing.JOptionPane.showMessageDialog(null, "Password is required", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
      return false;
    } else {
      return true;
    }
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set default theme */
    app.Global.setDefaultTheme();

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      new LoginFrame().setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnLogin;
  private javax.swing.JLabel lblItemImagePreview;
  private javax.swing.JLabel lblPassword;
  private javax.swing.JLabel lblTitle;
  private javax.swing.JLabel lblUsername;
  private javax.swing.JPanel pnlContainer;
  private javax.swing.JPasswordField txtPassword;
  private javax.swing.JTextField txtUsername;
  // End of variables declaration//GEN-END:variables
}
